### ISSUE TITLE
Got hacked.

### ISSUE THREAD

**Issue by Cossoe** [Gilwyad/mailnesia.com#38]
Some hacker hacked my email and used a @mailnesia.com email as a recovery address. Completely stole my account and all my accounts associated to that email..

**Comment by HarrisonChris** [comment]
I am an IT service provider and I have seen 5 clients so far get hacked from mailnesia.com... It needs to be reported for harboring criminals.

**Comment by Gilwyad** [comment]
- How does one get hacked from mailnesia.com ? 
- How is this not possible on the countless disposable email alternatives such as mailinator or 10 minute mail ?
- What can I do to help?

**Comment by HarrisonChris** [comment]
It was an email address on mailnesia.com, not FROM mailnesia.com as I stated first. The hacker/s used email addresses from this domain as a recovery address in the legitimate accounts they hacked and hijacked. If mailnesia.com stands behind the "anonymous" reputation then I assume I am out of luck in asking for IP address info of these accounts in question in order to prosecute the perp/s...

**Comment by Gilwyad** [comment]
I'd love to help but currently there's only one week worth of logs so I doubt it would be of any use.

I'm thinking there should be a publicly available list of IPs that visited a mailbox, maybe I'll implement it.
